//
//  SignupInteractor.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignupInteractor {

    weak var presenter: SignupInteractorOutputProtocol!
}

// MARK: - SignupInteractorInputProtocol

extension SignupInteractor: SignupInteractorInputProtocol {
    
}
