//
//  SignupViewController.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignupViewController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!

	var presenter: SignupPresenterProtocol!

    // MARK: - Life Cycle
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        addObserverKeyboardNotificatons()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification, object: nil)
    }
    
    // MARK: - Keyboard Notifications
    
    private func addObserverKeyboardNotificatons() {
        
        NotificationCenter.default.addObserver(forName: UIResponder.keyboardWillShowNotification,
                                               object: nil,
                                               queue: nil) { (notification) in
                                                guard let keyboardRect =  notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
                                                self.tableView.contentInset.bottom = keyboardRect.size.height
        }
        
        NotificationCenter.default.addObserver(forName: UIResponder.keyboardWillHideNotification,
                                               object: nil,
                                               queue: nil) { (notification) in
                                                self.tableView.contentInset.bottom = 0
        }
    }
    
    // MARK: - Actions
    
    @IBAction func onSignUpButton(_ sender: UIButton) {
        presenter.signUpAction()
    }

}


// MARK: - SignupViewProtocol

extension SignupViewController: SignupViewProtocol {
    
}

// MARK: - UITableViewDataSource

extension SignupViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.cellCount
    }
    
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: TextFieldCell.identifier, for: indexPath) as! TextFieldCell
        cell.model = presenter.dataForIndexPath(indexPath)
        return cell
    }
}

// MARK: - UITableViewDelegate

extension SignupViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return presenter.cellHeight
    }
}

// MARK: - StoryboardInitiable

extension SignupViewController: StoryboardInitiable {}
