//
//  WelcomePresenter.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WelcomePresenter {

    weak private var view: WelcomeViewProtocol!
    var interactor: WelcomeInteractorInputProtocol!
    private let router: WelcomeWireframeProtocol

    init(interface: WelcomeViewProtocol, interactor: WelcomeInteractorInputProtocol?, router: WelcomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - WelcomePresenterProtocol

extension WelcomePresenter: WelcomePresenterProtocol {
    
    // Actions
    
    func actionLoginWithPhone() {
        LoginRouter.presenLoginModule(from: view as! UIViewController)
    }
    
    func actionNext() {
        SignupRouter.presenSignUpModule(from: view as! UIViewController)
    }
}

// MARK: - WelcomeInteractorOutputProtocol

extension WelcomePresenter: WelcomeInteractorOutputProtocol {
    
}
