//
//  WelcomeRouter.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WelcomeRouter {

    // MARK: - Private
    
    private static func createModule() -> UIViewController {
        let view = WelcomeViewController.initiate(storyboardType: .enter)
        let interactor = WelcomeInteractor()
        let router = WelcomeRouter()
        let presenter = WelcomePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter

        return view
    }
    
    // MARK: - Public
    
    static func presentWelcomeModule() {
        let vc = WelcomeRouter.createModule()
        let navigationController = UINavigationController(rootViewController: vc)
        let window = UIApplication.shared.delegate?.window ?? nil
        window?.rootViewController = navigationController
        window?.makeKeyAndVisible()
    }
}

// MARK: - WelcomeWireframeProtocol

extension WelcomeRouter: WelcomeWireframeProtocol {
    
}
