//
//  SplashPresenter.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashPresenter {
    
    weak fileprivate var view: SplashViewProtocol!
    var interactor: SplashInteractorInputProtocol!
    fileprivate let router: SplashWireframeProtocol
    
    init(interface: SplashViewProtocol, interactor: SplashInteractorInputProtocol!, router: SplashWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

// MARK: - SplashPresenterProtocol

extension SplashPresenter: SplashPresenterProtocol {
    func showSignUp() {
//        WelcomeRouter.presentWelcomeModule()
    }
}

// MARK: - SplashInteractorOutputProtocol

extension SplashPresenter: SplashInteractorOutputProtocol {
    
}
