//
//  SplashInteractor.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashInteractor {
    
    weak var presenter: SplashInteractorOutputProtocol!
}

// MARK: - SplashInteractorInputProtocol

extension SplashInteractor: SplashInteractorInputProtocol {
    
}
