//
//  SplashViewController.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AWSMobileClient

class SplashViewController: UIViewController {
    
    var presenter: SplashPresenterProtocol!
    
    // MARK: - Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
//        presenter.showSignUp()
        
        
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let userState = userState {
                switch(userState){
                case .signedIn:
                    DispatchQueue.main.async {
                        print("signedIn")
                        TestViewController.presentBaseTestViewController()
                    }
                case .signedOut:
                    DispatchQueue.main.async {
                        print("signedOut")
                        WelcomeRouter.presentWelcomeModule()
                    }
                default:
                    AWSMobileClient.sharedInstance().signOut()
                }
                
            } else if let error = error {
                print(error.localizedDescription)
            }
        }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.tabBarController?.tabBar.isHidden = true
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.tabBarController?.tabBar.isHidden = false
    }
}

// MARK: - SplashViewProtocol

extension SplashViewController: SplashViewProtocol {
    
}

// MARK: - StoryboardInitiable

extension SplashViewController: StoryboardInitiable {}
