//
//  SplashProtocols.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SplashWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol SplashPresenterProtocol: class {
    
    var interactor: SplashInteractorInputProtocol! { get set }
    
    func showSignUp()
}

//MARK: Interactor -
protocol SplashInteractorOutputProtocol: class {
    
    /* Interactor -> Presenter */
}

protocol SplashInteractorInputProtocol: class {
    
    var presenter: SplashInteractorOutputProtocol!  { get set }
    
    /* Presenter -> Interactor */
}

//MARK: View -
protocol SplashViewProtocol: class {
    
    var presenter: SplashPresenterProtocol!  { get set }
    
    /* Presenter -> ViewController */
}

