//
//  SplashRouter.swift
//  Sift
//
//  Created Денис Фролов on 25/01/2019.
//  Copyright © 2019 Denis Frolov. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashRouter {
    
    // MARK: - Private
    
    private static func createModule() -> UIViewController {
        let view = SplashViewController.initiate(storyboardType: .main)
        let interactor = SplashInteractor()
        let router = SplashRouter()
        let presenter = SplashPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
    
    // MARK: - Public
    
    static func presentSplashModule(from window: UIWindow?) {
        let vc = SplashRouter.createModule()
        let navigationController = UINavigationController(rootViewController: vc)
        window?.rootViewController = navigationController
        window?.makeKeyAndVisible()
    }
}

// MARK: - SplashWireframeProtocol

extension SplashRouter: SplashWireframeProtocol {
    
}
